[profile.default]
src = 'contracts'
out = 'out'
ffi = true
libs = ['lib']
optimizer = true
optimizer_runs = 1_000_000 
solc = "0.8.19"
fs_permissions = [{ access = "read", path = "./test/data/"}]

[profile.default.optimizer_details]
constantOptimizer = false 
yul = false 

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

# Configures permissions for cheatcodes that touch the filesystem like `vm.writeFile`
# `access` restricts how the `path` can be accessed via cheatcodes
#    `read-write` | `true`   => `read` + `write` access allowed (`vm.readFile` + `vm.writeFile`)
#    `none`| `false` => no access
#    `read` => only read access (`vm.readFile`)
#    `write` => only write access (`vm.writeFile`)
# The `allowed_paths` further lists the paths that are considered, e.g. `./` represents the project root directory
# By default _no_ fs access permission is granted, and _no_ paths are allowed
# following example enables read access for the project dir _only_:
#       `fs_permissions = [{ access = "read", path = "./"}]`

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
